CREATE TABLE "MEMBER" (
	"ID"	VARCHAR2(20)		NOT NULL,
	"PASSWORD"	VARCHAR2(30)	NOT NULL,
	"NAME"	VARCHAR2(30)		NOT NULL,
	"PHONE"	VARCHAR2(20)		NOT NULL,
	"BIRTH_DATE"	DATE		NOT NULL
);

CREATE TABLE "SEAT" (
	"SEAT_CODE"	VARCHAR2(3)		NOT NULL,
	"SCREEN_NO"	NUMBER(3)		NOT NULL
);

CREATE TABLE "SCREEN" (
	"SCREEN_NO"	NUMBER(3)		NOT NULL,
	"SCREEN_NAME"	VARCHAR2(30)		NULL
);

CREATE TABLE "TICKET" (
	"TICKET_NO"	NUMBER(3)		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL,
	"TIME_CODE"	NUMBER(3)		NOT NULL,
	"PAY_COST"	NUMBER(10)		NOT NULL,
	"ORDER_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"TICKET_STATUS"	NUMBER(1)	DEFAULT 1	NOT NULL
);

CREATE TABLE "MOVIE" (
	"MOVIE_NO"	NUMBER(3)		NOT NULL,
	"TITLE"	VARCHAR2(300)		NOT NULL,
	"OPEN_DATE"	DATE		NOT NULL,
	"DIRECTOR"	VARCHAR2(300)		NOT NULL,
	"ACTORS"	VARCHAR2(300)		NOT NULL,
	"GENRE"	VARCHAR2(300)		NOT NULL,
	"RUNNINGTIME"	VARCHAR2(20)		NOT NULL,
	"SUMMARY"	VARCHAR2(4000)		NOT NULL,
	"RATING"	VARCHAR2(20)		NOT NULL,
	"POSTER_IMAGE"	VARCHAR2(4000)		NOT NULL
);

CREATE TABLE "TIME" (
	"TIME_CODE"	NUMBER(3)		NOT NULL,
	"SCREEN_NO"	NUMBER(3)		NOT NULL,
	"MOVIE_NO"	NUMBER(3)		NOT NULL,
	"START_TIME"	VARCHAR2(5)		NOT NULL,
	"END_TIME"	    VARCHAR2(5)		NOT NULL,
	"MOVIE_DATE"	DATE		NOT NULL
);

CREATE TABLE "REVIEW" (
	"REVIEW_NO"	NUMBER(4)		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL,
	"MOVIE_NO"	NUMBER(20)		NOT NULL,
	"SCORE"	NUMBER(1)	DEFAULT 0	NOT NULL,
	"REVIEW_COMMENT"	VARCHAR2(500)		NOT NULL
);

CREATE TABLE "BOOKED_SEAT" (
	"TICKET_NO"	NUMBER(3)		NOT NULL,
	"SEAT_CODE"	VARCHAR2(3)		NOT NULL,
	"SCREEN_NO"	NUMBER(3)		NOT NULL
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"ID"
);

ALTER TABLE "SEAT" ADD CONSTRAINT "PK_SEAT" PRIMARY KEY (
	"SEAT_CODE",
	"SCREEN_NO"
);

ALTER TABLE "SCREEN" ADD CONSTRAINT "PK_SCREEN" PRIMARY KEY (
	"SCREEN_NO"
);

ALTER TABLE "TICKET" ADD CONSTRAINT "PK_TICKET" PRIMARY KEY (
	"TICKET_NO"
);

ALTER TABLE "MOVIE" ADD CONSTRAINT "PK_MOVIE" PRIMARY KEY (
	"MOVIE_NO"
);

ALTER TABLE "TIME" ADD CONSTRAINT "PK_TIME" PRIMARY KEY (
	"TIME_CODE"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"REVIEW_NO"
);

ALTER TABLE "BOOKED_SEAT" ADD CONSTRAINT "PK_BOOKED_SEAT" PRIMARY KEY (
	"TICKET_NO",
	"SEAT_CODE",
	"SCREEN_NO"
);

ALTER TABLE "SEAT" ADD CONSTRAINT "FK_SCREEN_TO_SEAT_1" FOREIGN KEY (
	"SCREEN_NO"
)
REFERENCES "SCREEN" (
	"SCREEN_NO"
);

ALTER TABLE "TICKET" ADD CONSTRAINT "FK_MEMBER_TO_TICKET_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
) ON DELETE CASCADE;

ALTER TABLE "TICKET" ADD CONSTRAINT "FK_TIME_TO_TICKET_1" FOREIGN KEY (
	"TIME_CODE"
)
REFERENCES "TIME" (
	"TIME_CODE"
) ON DELETE CASCADE;

ALTER TABLE "TIME" ADD CONSTRAINT "FK_SCREEN_TO_TIME_1" FOREIGN KEY (
    "SCREEN_NO"
)
REFERENCES "SCREEN" (
    "SCREEN_NO"
) ON DELETE CASCADE;

ALTER TABLE "TIME" ADD CONSTRAINT "FK_MOVIE_TO_TIME_1" FOREIGN KEY (
    "MOVIE_NO"
)
REFERENCES "MOVIE" (
    "MOVIE_NO"
) ON DELETE CASCADE;

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
) ON DELETE CASCADE;

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_MOVIE_TO_REVIEW_1" FOREIGN KEY (
	"MOVIE_NO"
)
REFERENCES "MOVIE" (
	"MOVIE_NO"
) ON DELETE CASCADE;

ALTER TABLE "BOOKED_SEAT" ADD CONSTRAINT "FK_TICKET_TO_BOOKED_SEAT_1" FOREIGN KEY (
	"TICKET_NO"
)
REFERENCES "TICKET" (
	"TICKET_NO"
) ON DELETE CASCADE;

ALTER TABLE "BOOKED_SEAT" ADD CONSTRAINT "FK_SEAT_TO_BOOKED_SEAT_1" FOREIGN KEY (
	"SEAT_CODE",
    "SCREEN_NO"
)
REFERENCES "SEAT" (
	"SEAT_CODE",
    "SCREEN_NO"
);

CREATE SEQUENCE TICKET_SEQ
INCREMENT BY 1
START WITH 100;

CREATE SEQUENCE REVIEW_SEQ
INCREMENT BY 1
START WITH 100;